# copied over from commit f6d73b, got 97.936 on leader board
ALL_IMPORTANT_WORDS = ["chef", "manager", "cook", "cafe", "barista", "staff", "kitchen", "hand", "time", "restaurant",
                       "consultant", "travel", "cleaner", "assistant", "sale", "casual", "bar", "food", "service",
                       "attendant", "full", "head", "team", "sou", "rounder", "wait", "sydney", "member", "supervisor",
                       "housekeeper", "de", "start", "work", "partie", "beverage", "cbd", "hospitality", "hotel",
                       "waiter", "hour", "venue", "busy", "customer", "apprentice", "front", "house", "experience",
                       "melbourne", "position", "driver", "week", "centre", "waitres", "catering", "event", "busines",
                       "delivery", "pizza", "job", "senior", "breakfast", "day", "opportunity", "brisbane", "corporate",
                       "location", "junior", "sandwich", "commi", "year", "pastry", "north", "cleaning", "waitstaff",
                       "executive", "agent", "great", "night", "coffee", "duty", "receptionist", "general", "office",
                       "care", "weekend", "domestic", "suburb", "allrounder", "waiting", "indian", "housekeeping",
                       "gaming", "kitchenhand", "baker", "flight", "maker", "floor", "south", "coordinator", "role",
                       "guest", "bartender", "join", "hill", "professional", "group", "specialist", "officer", "area",
                       "crew", "seeking", "city", "italian", "shift", "asap", "shop", "hiring", "pub", "development",
                       "leader", "room", "japanese", "inner", "reservation", "operation", "nanny", "function", "retail",
                       "park", "worker", "live", "top", "perth", "person", "west", "employment", "store", "dining",
                       "coast", "resort", "nsw", "childcare", "bay", "urgent", "bondi", "career", "sponsorship",
                       "commercial", "bistro", "beach", "club", "cdp", "fun", "northern", "industry", "friday",
                       "cruise", "high", "mon", "eastern", "sushi", "student", "st", "short", "passionate",
                       "backpacker", "order", "airport", "demi", "company", "asian", "security", "contract", "lunch",
                       "cuisine", "host", "star", "skill", "brand", "dishwasher", "pair", "au", "grill", "people",
                       "recruitment", "trainee", "canberra", "level", "international", "adelaide", "cashier", "account",
                       "couple", "cocktail", "management", "surround", "super", "modern", "production", "wholesale",
                       "bakery", "exciting", "counter", "manly", "school", "personal", "gold", "luxury", "support",
                       "opportunitie", "point", "café", "monday", "east", "valley", "iconic", "marketing", "takeaway",
                       "urgently", "australia", "fast", "residential", "thi", "cove", "fri", "representative",
                       "quality", "funky", "concierge", "conference", "fine", "chatswood", "progression", "national",
                       "holiday", "artist", "amazing", "hat", "training", "steward", "operator", "calling", "qld",
                       "port", "waitress", "expert", "country", "parramatta", "life", "darwin", "permanent", "lane",
                       "friendly", "snr", "island", "motel", "guard", "tour", "analyst", "design", "porter", "nurse",
                       "jnr", "good", "boutique", "help", "richmond", "shore", "chefs", "vic", "maintenance", "tiler",
                       "require", "central", "car", "energetic", "burger", "tavern", "private", "shopping",
                       "waitperson", "reception", "month", "outgoing", "small", "online", "accommodation", "sponsorsh",
                       "tandoori", "director", "wine", "creative", "web", "leisure", "therapist", "family", "health",
                       "working", "site", "kilda", "remote", "opening", "fb", "change", "wa", "award", "salary",
                       "western", "market", "beache", "ryde", "solution", "hol", "housekeepers", "desk", "product",
                       "call", "cairn", "newport", "apply", "best", "multi", "balance", "child", "laundry", "prep",
                       "administration", "hairdresser", "leading", "rep", "multiple", "sport", "visa", "winning", "tv",
                       "relief", "macquarie", "evening", "thai", "administrator", "free", "love", "lot", "hr", "salad",
                       "fulltime", "highly", "close", "farm", "advisor", "adventure", "chinese", "foh", "hunter",
                       "royal", "waitresse", "plaza", "auditor", "street", "controller", "teacher", "banquet",
                       "brighton", "brunswick", "lake", "interest", "pyrmont", "marrickville", "cellar", "sunshine",
                       "weneedanannycomau", "subway", "young", "term", "guide", "french", "tab", "fifo", "southern",
                       "entry", "client", "harbour", "hurstville", "expression", "lead", "victoria", "regional",
                       "superstar", "bankstown", "trainer", "growth", "temp", "local", "early", "tender", "rsm",
                       "party", "vip", "today", "ski", "paid", "coogee", "hospital", "utility", "cole", "spa", "surry",
                       "cooking", "popular", "newcastle", "inn", "fresh", "lounge", "dish", "earn", "well", "relocate",
                       "banker", "dan", "guru", "public", "door", "morning", "gastro", "outbound", "dee",
                       "entertainment", "la", "financial", "airbnb", "festival", "mobile", "server", "helper",
                       "concept", "murphy", "inbound", "reliable", "larder", "beautiful", "sun", "canteen", "excellent",
                       "king", "summer", "maid", "seek", "sunday", "stunning", "money", "exp", "locum", "daytime",
                       "spring", "confident", "yarra", "bayside", "keeper", "hard", "preparation", "fish", "traveller",
                       "saturday", "enthusiastic", "beauty", "carlton", "dynamic", "tomorrow", "station", "caribbean",
                       "juice", "project", "curry", "carte", "westfield", "hostes", "deli", "cool", "hostel", "rock",
                       "roadhouse", "fitzroy", "uni", "facility", "van", "officer", "project", "analyst", "account",
                       "support", "engineer", "nurse", "accountant", "developer", "administrator", "contract", "store",
                       "development", "specialist", "worker", "operator", "administration", "property", "financial",
                       "labourer", "marketing", "technician", "teacher", "commercial", "representative", "leader",
                       "management", "retail", "health", "finance", "director", "recruitment", "designer", "digital",
                       "nsw", "lead", "associate", "level", "system", "operation", "hr", "month", "civil", "personal",
                       "medical", "technical", "advisor", "site", "graduate", "architect", "clinical", "data",
                       "construction", "legal", "client", "carpenter", "mechanic", "school", "super", "credit",
                       "program", "maintenance", "warehouse", "fitter", "planner", "lawyer", "truck", "payroll",
                       "forklift", "community", "educator", "solution", "software", "area", "product", "design",
                       "security", "communication", "production", "early", "clerk", "residential", "electrician",
                       "building", "permanent", "practice", "gp", "secretary", "trade", "leading", "therapist", "high",
                       "national", "media", "woolworth", "trainee", "industry", "fashion", "brand", "professional",
                       "carte", "barista", "wait", "tandoor", "waterside", "wok", "bar", "tandoori", "espresso",
                       "jamie", "curry", "mediterranean", "partie", "sandwichhand", "sake", "mixologist", "cocktail",
                       "sou", "brasserie", "waiter", "chef", "cafe", "worklife", "foodcourt", "airbnb", "baristas",
                       "bean", "housekeepers", "café", "portsea", "nights", "cooks", "batista", "teppanyaki",
                       "intercontinental", "craving", "reservation", "cook", "cafÉ", "glassy", "lobby", "bistro",
                       "banquet", "cafeteria", "grill", "lunch", "reservations", "griller", "skycity", "waitperson",
                       "boardroom", "eatery", "cuisine", "breakfast", "pastry", "muffin", "woodfire", "parade", "steak",
                       "sandwich", "guest", "commis", "buffet", "pier", "salesgirl", "daintree", "waitress",
                       "waitstaff", "waiters", "laneway", "pavilion", "residency", "flight", "dining", "pullman",
                       "beachfront", "chapter", "sashimi", "renown", "ramen", "madame", "obsession", "restaurant",
                       "beverage", "pasta", "karaoke", "waitressing", "waitering", "pakistani", "mex", "brunch",
                       "tavern", "indian", "housecleaner", "cruiseabout", "housekeeping", "gastro", "maid", "bartender",
                       "pita", "pref", "mexican", "demi", "cooker", "cruising"]

ALL_IMPORTANT_WORDS_ABSTRACT = ["customer service", "customer complaints", "products according", "passionate about",
                                "interpersonal skills", "customers with", "kitchen hand", "training will",
                                "growing sales", "orders from", "efficient manner", "personal hygiene",
                                "helping others", "handling customer", "serves customers", "regularly using",
                                "demonstrates teamwork", "treating fellow", "demonstrates belief", "supports other",
                                "Sound communication", "hygiene guidelines", "takes orders", "company products",
                                "every shift", "designated work", "courteous manner", "following correct",
                                "before being", "complies with", "situations within", "manner reflecting",
                                "items/serve/deliver company", "prepare/store/pack food", "member prepare/store/pack",
                                "unsafe conditions", "correct cash", "equipment safely", "behavioural standards",
                                "certified before", "demonstrates accountability", "suggestive selling",
                                "company procedures", "immediately reports", "member orientation", "dresses according",
                                "serious/difficult customer", "remedies minor", "rotates food", "achieves champs",
                                "shift goals", "minor unsafe", "station alone", "service acts", "customer maniac",
                                "restaurant basics", "product stocked", "member training", "positive energy",
                                "restrooms clean", "keeps product", "unsafe situations", "designated equipment",
                                "knows restaurant", "flight centre", "rapidly expanding", "house cleaning",
                                "communication skills", "expanding cleaning", "exceptional customer",
                                "cleaning platform", "trustworthy individuals", "previous experience",
                                "experience working", "award winning", "travel sales", "excellent customer",
                                "under pressure", "quality food", "sales consultants", "service skills", "their travel",
                                "service provided", "successful travel", "travel needs", "loyal customers",
                                "restaurant manager", "ongoing service", "makes flight", "booking online",
                                "immediate start", "chef", "manager", "cook", "cafe", "barista", "staff", "kitchen",
                                "hand", "time", "restaurant", "consultant", "travel", "cleaner", "assistant", "sale",
                                "casual", "bar", "food", "service", "attendant", "full", "head", "team", "sou",
                                "rounder", "wait", "sydney", "member", "supervisor", "housekeeper", "de", "start",
                                "work", "partie", "beverage", "cbd", "hospitality", "hotel", "waiter", "hour", "venue",
                                "busy", "customer", "apprentice", "front", "house", "experience", "melbourne",
                                "position", "driver", "week", "centre", "waitres", "catering", "event", "busines",
                                "delivery", "pizza", "job", "senior", "breakfast", "day", "opportunity", "brisbane",
                                "corporate", "location", "junior", "sandwich", "commi", "year", "pastry", "north",
                                "cleaning", "waitstaff", "executive", "agent", "great", "night", "coffee", "duty",
                                "receptionist", "general", "office", "care", "weekend", "domestic", "suburb",
                                "allrounder", "waiting", "indian", "housekeeping", "gaming", "kitchenhand", "baker",
                                "flight", "maker", "floor", "south", "coordinator", "role", "guest", "bartender",
                                "join", "hill", "professional", "group", "specialist", "officer", "area", "crew",
                                "seeking", "city", "italian", "shift", "asap", "shop", "hiring", "pub", "development",
                                "leader", "room", "japanese", "inner", "reservation", "operation", "nanny", "function",
                                "retail", "park", "worker", "live", "top", "perth", "person", "west", "employment",
                                "store", "dining", "coast", "resort", "nsw", "childcare", "bay", "urgent", "bondi",
                                "career", "sponsorship", "commercial", "bistro", "beach", "club", "cdp", "fun",
                                "northern", "industry", "friday", "cruise", "high", "mon", "eastern", "sushi",
                                "student", "st", "short", "passionate", "backpacker", "order", "airport", "demi",
                                "company", "asian", "security", "contract", "lunch", "cuisine", "host", "star", "skill",
                                "brand", "dishwasher", "pair", "au", "grill", "people", "recruitment", "trainee",
                                "canberra", "level", "international", "adelaide", "cashier", "account", "couple",
                                "cocktail", "management", "surround", "super", "modern", "production", "wholesale",
                                "bakery", "exciting", "counter", "manly", "school", "personal", "gold", "luxury",
                                "support", "opportunitie", "point", "café", "monday", "east", "valley", "iconic",
                                "marketing", "takeaway", "urgently", "australia", "fast", "residential", "thi", "cove",
                                "fri", "representative", "quality", "funky", "concierge", "conference", "fine",
                                "chatswood", "progression", "national", "holiday", "artist", "amazing", "hat",
                                "training", "steward", "operator", "calling", "qld", "port", "waitress", "expert",
                                "country", "parramatta", "life", "darwin", "permanent", "lane", "friendly", "snr",
                                "island", "motel", "guard", "tour", "analyst", "design", "porter", "nurse", "jnr",
                                "good", "boutique", "help", "richmond", "shore", "t", "chefs", "vic", "maintenance",
                                "tiler", "require", "central", "car", "energetic", "burger", "tavern", "private",
                                "shopping", "waitperson", "reception", "month", "outgoing", "small", "online",
                                "accommodation", "sponsorsh", "tandoori", "director", "wine", "creative", "web",
                                "leisure", "therapist", "family", "health", "working", "site", "kilda", "remote",
                                "opening", "fb", "change", "wa", "award", "salary", "western", "market", "beache",
                                "ryde", "solution", "hol", "housekeepers", "desk", "product", "call", "cairn",
                                "newport", "apply", "best", "multi", "balance", "child", "laundry", "prep",
                                "administration", "hairdresser", "leading", "rep", "multiple", "sport", "visa",
                                "winning", "tv", "relief", "macquarie", "evening", "thai", "administrator", "free",
                                "love", "lot", "hr", "salad", "fulltime", "highly", "close", "farm", "advisor",
                                "adventure", "chinese", "foh", "hunter", "royal", "waitresse", "plaza", "auditor",
                                "street", "controller", "teacher", "banquet", "brighton", "brunswick", "lake",
                                "interest", "pyrmont", "marrickville", "cellar", "sunshine", "weneedanannycomau",
                                "subway", "young", "term", "guide", "french", "tab", "fifo", "southern", "entry",
                                "client", "harbour", "hurstville", "expression", "lead", "victoria", "regional",
                                "superstar", "bankstown", "trainer", "growth", "temp", "local", "early", "tender",
                                "rsm", "party", "vip", "today", "ski", "paid", "coogee", "hospital", "utility", "cole",
                                "spa", "surry", "cooking", "popular", "newcastle", "inn", "fresh", "lounge", "dish",
                                "earn", "well", "relocate", "banker", "dan", "guru", "public", "door", "morning",
                                "gastro", "outbound", "dee", "entertainment", "la", "financial", "airbnb", "festival",
                                "mobile", "server", "helper", "concept", "murphy", "inbound", "reliable", "larder",
                                "beautiful", "sun", "canteen", "excellent", "king", "summer", "maid", "seek", "sunday",
                                "mt", "stunning", "money", "bu", "exp", "locum", "daytime", "spring", "confident",
                                "yarra", "bayside", "keeper", "hard", "preparation", "fish", "traveller", "saturday",
                                "enthusiastic", "beauty", "carlton", "dynamic", "tomorrow", "station", "caribbean",
                                "juice", "project", "curry", "carte", "westfield", "hostes", "deli", "cool", "hostel",
                                "rock", "roadhouse", "fitzroy", "uni", "facility", "van", "officer", "project",
                                "analyst", "account", "support", "engineer", "nurse", "accountant", "developer",
                                "administrator", "contract", "store", "development", "specialist", "worker", "operator",
                                "administration", "property", "financial", "labourer", "marketing", "technician",
                                "teacher", "commercial", "representative", "leader", "management", "retail", "health",
                                "finance", "director", "recruitment", "designer", "digital", "nsw", "lead", "associate",
                                "level", "system", "operation", "hr", "month", "civil", "personal", "medical",
                                "technical", "advisor", "site", "graduate", "architect", "clinical", "data",
                                "construction", "legal", "client", "carpenter", "mechanic", "school", "super", "credit",
                                "program", "maintenance", "warehouse", "fitter", "planner", "lawyer", "truck",
                                "payroll", "forklift", "community", "educator", "solution", "software", "area",
                                "product", "design", "security", "communication", "production", "early", "clerk",
                                "residential", "electrician", "building", "permanent", "practice", "gp", "secretary",
                                "trade", "leading", "therapist", "high", "national", "media", "woolworth", "trainee",
                                "industry", "fashion", "brand", "professional"]

IMPORTANT_WORD_RAW_LOCATIONS = ["chef", "manager", "cafe", "barista", "kitchen", "restaurant", "consultant", "travel",
                                "bar", "service", "attendant", "sou", "housekeeper", "partie", "beverage",
                                "hospitality", "hotel", "waitres", "catering", "delivery", "corporate", "pastry",
                                "executive"]
